# ===================================================================
#
# _|  _|_|    _|_|_|  _|_|_|      _|_|_|    _|_|    _|  _|_|
# _|_|      _|    _|  _|    _|  _|    _|  _|_|_|_|  _|_|
# _|        _|    _|  _|    _|  _|    _|  _|        _|
# _|          _|_|_|  _|    _|    _|_|_|    _|_|_|  _|
#                                     _|
#                                 _|_|
#
# See: https://wiki.archlinux.org/title/Ranger
# ===================================================================

# Only settings that differ from the defaults are listed.

set show_hidden true
set preview_images_method kitty
set unicode_ellipsis true
set colorscheme solarized
set status_bar_on_top true
set draw_borders both
set hostname_in_titlebar false
set tilde_in_titlebar true

# ":cd /u/lo/b<tab>" expands to ":cd /usr/local/bin"
set cd_tab_fuzzy true
